/**
 * Digital Archive Amigo App Server API
 * An interface to a amigo app of distributed nodes for personal storage.
 *
 * OpenAPI spec version: 1.0.4
 * Contact: rosborne@coredb.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SocialLink { 
    link?: string;
    category?: string;
}